from crewai import Crew, Process
from agents.jd_analyst import get_jd_analyst_agent, create_jd_analysis_task
from agents.resume_cl_agent import get_resume_cl_agent, create_resume_cl_task
from agents.messaging_agent import get_messaging_agent, create_messaging_task
from utils.tracking import log_application, save_cover_letter_file

def load_resume(path="data/sample_resume.txt"):
    """Safely loads user resume text."""
    try:
        with open(path, 'r', encoding='utf-8') as file:
            return file.read()
    except FileNotFoundError:
        print(f"⚠️ Warning: Resume file not found at {path}. Using placeholder context.")
        return "Experienced Software Engineer with proficiency in Python, C++, and Web Frameworks."

def extract_between_markers(text, start, end=None):
    """Extracts target sections generated by agents using bounding tags."""
    try:
        if start not in text:
            return "Marker not found"
        start_idx = text.index(start) + len(start)
        
        if end and end in text:
            end_idx = text.index(end, start_idx)
            return text[start_idx:end_idx].strip()
        else:
            return text[start_idx:].strip()
    except ValueError:
        return "Parsing error while extracting content"

def run_pipeline(job_data, resume_text, user_bio):
    """
    Orchestrates the sequential CrewAI execution.
    Takes the cleaned job data dictionary from usajobs_api.py.
    """
    # FIXED: Extracting directly from our cleaned, flattened usajobs_api dictionary format
    job_title = job_data.get('title', 'Unknown Position')
    agency_name = job_data.get('agency', 'Unknown Agency')
    
    # Compile a comprehensive context block out of our cleaned job data fields
    job_summary = (
        f"Job Title: {job_title}\n"
        f"Agency: {agency_name}\n"
        f"Location: {job_data.get('location', 'Remote')}\n"
        f"Summary: {job_data.get('summary', '')}\n"
        f"Duties/Qualifications: {job_data.get('qualifications', '') or job_data.get('duties', '')}"
    )

    # Initialize Gemini-powered agents
    jd_agent = get_jd_analyst_agent()
    resume_agent = get_resume_cl_agent()
    message_agent = get_messaging_agent()

    # Define tasks with optimized inputs
    jd_task = create_jd_analysis_task(jd_agent, job_summary)
    resume_task = create_resume_cl_task(resume_agent, job_summary, resume_text)
    message_task = create_messaging_task(message_agent, job_summary, agency_name, user_bio)

    # Assemble and trigger the multi-agent Crew
    crew = Crew(
        agents=[jd_agent, resume_agent, message_agent],
        tasks=[jd_task, resume_task, message_task],
        process=Process.sequential,
        verbose=True  # Enables console streaming logs so you can monitor progress
    )
    
    # Run the processing workflow
    result = crew.kickoff()
    
    # Convert result to string for safe text manipulation
    result_str = str(result)

    # Extract specific segments based on formatting rules provided to the resume agent
    resume_summary = extract_between_markers(result_str, "<<RESUME_SUMMARY>>", "<<COVER_LETTER>>")
    cover_letter = extract_between_markers(result_str, "<<COVER_LETTER>>")

    # Fallback to standard result slice if formatting markers were skipped by LLM
    if resume_summary == "Marker not found" or cover_letter == "Marker not found":
        print("⚠️ Formatting markers not matched exactly. Parsing fallback applied.")
        resume_summary = f"Tailored application for {job_title}"
        cover_letter = result_str

    # Log and tracking execution
    log_application(job_title, agency_name, resume_summary)
    save_cover_letter_file(job_title, cover_letter)
    
    print("\n=== PIPELINE PROCESSING COMPLETE ===\n")
    return result_str


if __name__ == "__main__":
    # Test block allowing isolated standalone execution of orchestrator.py
    mock_job = {
        "title": "Software Engineer",
        "agency": "Department of Transportation",
        "location": "Remote",
        "summary": "Looking for a Python developer with experience designing backends and APIs.",
        "qualifications": "Experience with Python, environment configuration, data pipelines."
    }
    
    mock_resume = "Gaurav. Core competencies: Python backend programming, C++, API integrations."
    mock_bio = "Software developer focusing on creating scalable automated pipelines."
    
    print("🚀 Running Orchestrator locally with mock configurations...")
    run_pipeline(mock_job, mock_resume, mock_bio)